name: Build and test wow-addon-updater

on:
  push:
    branches:
      - master
      - develop
      - release/*
  pull_request:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Run unit tests
        run: |
          pipenv run python -m unittest -v
